name: Update Horoscope Data

on:
  schedule:
    - cron: '0 0 * * *'  # Menjalankan setiap hari pada pukul 00:00 UTC
  workflow_dispatch:  # Bisa dijalankan manual juga

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Menggunakan Node.js versi terbaru

      - name: Install dependencies
        run: npm install node-fetch@2

      - name: Run update script
        env:
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
        run: |
          cat <<EOF > updateData.js
          const fetch = require('node-fetch');
          const fs = require('fs');

          const zodiacSign = "leo";  // Ubah sesuai kebutuhan
          const url = \`https://best-daily-astrology-and-horoscope-api.p.rapidapi.com/api/Detailed-Horoscope/?zodiacSign=\${zodiacSign}\`;

          const options = {
              method: 'GET',
              headers: {
                  'x-rapidapi-host': 'best-daily-astrology-and-horoscope-api.p.rapidapi.com',
                  'x-rapidapi-key': process.env.RAPIDAPI_KEY
              }
          };

          fetch(url, options)
              .then(response => response.json())
              .then(data => {
                  const updatedData = {
                      horoscope: data.horoscope || "No data available"
                  };
                  fs.writeFileSync('data.json', JSON.stringify(updatedData, null, 2));
                  console.log("Data updated successfully.");
              })
              .catch(error => {
                  console.error("Error fetching data:", error);
                  process.exit(1);
              });
          EOF

          node updateData.js

      - name: Commit and push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}  # Token GitHub Anda disimpan di GitHub Secrets
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git remote remove origin  # Menghapus remote yang lama
          git remote add origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git  # Menambah remote dengan token
          git fetch origin main
          git checkout main
          git add data.json
          git commit -m "Update horoscope data [skip ci]" || echo "No changes to commit"  # Menghindari error jika tidak ada perubahan
          git push origin main
