name: Update Horoscope Data

on:
  schedule:
    - cron: '0 0 * * *'  # Menjalankan setiap hari pada pukul 00:00 UTC
  workflow_dispatch:  # Bisa dijalankan manual juga

permissions:
  contents: write  # Memberikan izin menulis ke repository

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install node-fetch@2

      - name: Fetch horoscope data
        env:
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
        run: |
          cat <<EOF > updateData.js
          const fetch = require('node-fetch');
          const fs = require('fs');

          const zodiacSign = "leo";  // Ganti sesuai kebutuhan
          const url = \`https://best-daily-astrology-and-horoscope-api.p.rapidapi.com/api/Detailed-Horoscope/?zodiacSign=\${zodiacSign}\`;

          const options = {
              method: 'GET',
              headers: {
                  'x-rapidapi-host': 'best-daily-astrology-and-horoscope-api.p.rapidapi.com',
                  'x-rapidapi-key': process.env.RAPIDAPI_KEY
              }
          };

          fetch(url, options)
              .then(response => response.json())
              .then(data => {
                  const updatedData = {
                      horoscope: data.horoscope || "No data available"
                  };
                  fs.writeFileSync('data.json', JSON.stringify(updatedData, null, 2));
                  console.log("Data updated successfully.");
              })
              .catch(error => {
                  console.error("Error fetching data:", error);
                  process.exit(1);
              });
          EOF

          node updateData.js

      - name: Commit and push changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add data.json
          git commit -m "Update horoscope data [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
